//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rekompensaty.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HuntedAnimal : IEntityClass
    {
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime HuntDate { get; set; }
        public double Weight { get; set; }
        public decimal PricePerKilo { get; set; }
        public System.Guid AnimalTypeId { get; set; }
    
        public virtual User User { get; set; }
        public virtual AnimalType AnimalType { get; set; }
    }
}
