//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rekompensaty.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HuntedAnimal : IEntityClass
    {
        public string Id { get; set; }
        public string UserId { get; set; }
        public string HuntDate { get; set; }
        public double Weight { get; set; }
        public double PricePerKilo { get; set; }
        public string AnimalTypeId { get; set; }
        public long HuntingArea { get; set; }
        public Nullable<double> RevenueValue { get; set; }
    
        public virtual AnimalType AnimalType { get; set; }
        public virtual User User { get; set; }
    }
}
